"""Generate the published API and ER references from the running application models."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.main import app  # noqa: E402
from app.models import Base  # noqa: E402


def api_markdown(schema: dict) -> str:
    from fastapi.routing import APIRoute

    auth_by_operation = {}
    for route in app.routes:
        if not isinstance(route, APIRoute):
            continue
        calls = []
        pending = list(route.dependant.dependencies)
        while pending:
            dependency = pending.pop()
            calls.append(dependency.call)
            pending.extend(dependency.dependencies)
        protected = any(getattr(call, "__name__", "") == "current_user" for call in calls)
        roles = []
        for call in calls:
            if getattr(call, "__qualname__", "").startswith("require_roles.<locals>"):
                for cell in getattr(call, "__closure__", ()) or ():
                    value = cell.cell_contents
                    if isinstance(value, tuple) and all(isinstance(role, str) for role in value):
                        roles = list(value)
        for method in route.methods or ():
            auth_by_operation[(route.path, method.lower())] = (protected, roles)

    lines = [
        "# API reference",
        "",
        f"Generated from the FastAPI OpenAPI schema (version `{schema['openapi']}`, API `{schema['info']['version']}`).",
        "Request, response, and parameter schemas are from [openapi.json](openapi.json). The authentication and role notes below come from the same FastAPI route dependencies; protected operations require a valid `access_token` cookie.",
        "",
        "## Operations",
        "",
    ]
    for route, operations in schema["paths"].items():
        for method, operation in operations.items():
            if method not in {"get", "post", "put", "patch", "delete"}:
                continue
            lines += [f"### `{method.upper()} {route}`", ""]
            if operation.get("summary"):
                lines += [operation["summary"], ""]
            if operation.get("description"):
                lines += [operation["description"], ""]
            tags = operation.get("tags", [])
            if tags:
                lines += [f"- **Tags:** {', '.join(tags)}"]
            protected, roles = auth_by_operation.get((route, method), (False, []))
            lines += [f"- **Authentication:** {'Required (access_token cookie)' if protected else 'Public'}"]
            if roles:
                lines += [f"- **Role:** {', '.join(roles)}"]
            params = operation.get("parameters", [])
            if params:
                lines += ["", "| Parameter | In | Required | Schema |", "|---|---|---:|---|"]
                for p in params:
                    typ = p.get("schema", {}).get("type", "object")
                    fmt = p.get("schema", {}).get("format")
                    if fmt:
                        typ += f" ({fmt})"
                    lines.append(f"| `{p['name']}` | {p['in']} | {'yes' if p.get('required') else 'no'} | {typ} |")
            body = operation.get("requestBody", {}).get("content", {})
            if body:
                schemas = sorted(
                    {
                        media.get("schema", {}).get("$ref", "").split("/")[-1]
                        for media in body.values()
                        if media.get("schema", {}).get("$ref")
                    }
                )
                lines += ["", f"**Request body:** {', '.join(f'`{x}`' for x in schemas) or 'See OpenAPI schema.'}"]
            responses = operation.get("responses", {})
            if responses:
                lines += [
                    "",
                    "**Responses:** "
                    + "; ".join(f"`{code}` {response.get('description', '')}" for code, response in responses.items()),
                ]
            lines.append("")
    lines += [
        "## Schema types",
        "",
        "Payload property definitions and exact response schemas are maintained in [openapi.json](openapi.json) under `components.schemas`.",
        "",
    ]
    return "\n".join(lines)


def er_markdown() -> str:
    tables = Base.metadata.sorted_tables
    lines = [
        "# Data model",
        "",
        "This ER diagram is generated by `backend/scripts/generate_docs.py` from SQLAlchemy `Base.metadata`; it is not a manually maintained approximation.",
        "JSON fields (including concept prerequisite lists and path snapshots) intentionally have no relational edges.",
        "",
        "```mermaid",
        "erDiagram",
    ]
    names = {table.name: table.name.upper() for table in tables}
    for table in tables:
        lines.append(f"    {names[table.name]} {{")
        for column in table.columns:
            typ = str(column.type).lower().replace(" ", "_")
            marks = []
            if column.primary_key:
                marks.append("PK")
            if column.unique:
                marks.append("UK")
            if column.foreign_keys:
                marks.append("FK")
            suffix = f" {' '.join(marks)}" if marks else ""
            lines.append(f"        {typ} {column.name}{suffix}")
        lines.append("    }")
    for table in tables:
        for column in table.columns:
            for fk in column.foreign_keys:
                parent_name, parent_column = fk.target_fullname.split(".", 1)
                child_cardinality = "||" if column.primary_key else "o{"
                lines.append(f"    {names[parent_name]} ||--{child_cardinality} {names[table.name]} : {column.name}")
    lines += ["```", "", "## Model notes", ""]
    for table in tables:
        indexes = [idx.name for idx in table.indexes]
        if indexes:
            lines.append(f"- `{table.name}` indexes: {', '.join(f'`{index}`' for index in sorted(indexes))}.")
    lines += [
        "- Learner-owned rows reference `users.id`; the API obtains the owner from the authenticated cookie and does not accept a learner ID for these reads/writes.",
        "- `concepts.prerequisites`, question options/tags, path snapshots/revisions, and audit details are JSON columns.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    docs = ROOT / "docs"
    schema = app.openapi()
    (docs / "openapi.json").write_text(json.dumps(schema, indent=2) + "\n", encoding="utf-8")
    (docs / "API.md").write_text(api_markdown(schema), encoding="utf-8")
    (docs / "data-model.md").write_text(er_markdown(), encoding="utf-8")
    print(f"Generated OpenAPI for {len(schema['paths'])} paths and ER diagram for {len(Base.metadata.tables)} tables.")


if __name__ == "__main__":
    main()
